sudo: required
language: c
env:
  - CABALVER=1.24 GHCVER=8.0.2
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
  - ghc --version
  - cabal --version
  - travis_retry cabal update
install:
  - cabal sandbox init
  - cabal install --only-dependencies --force-reinstalls
script:
  - cabal build
  - cabal test
  - ./dist/build/blog/blog build
  - cabal sdist
cache:
  directories:
    - .cabal-sandbox
deploy:
    provider: s3
    access_key_id: AKIAJOMPPK5E3YBSZZAA
    secret_access_key:
        secure: J15oUmHCx4jAgEWgG69qKAcQFUlnxHAPqNdh6mSSO2Xx+55xKa7UaQlnI1LlBVyPYxwlmpUm8fsUIcURx3krN1P0TwJO9G6NmRG7AB23HEy6zH/fYWjYAkASDJEtGjk5fEXR9Vo4aJSAZd34RH3H/Lw68xdBoqi/gRSSIqKScUY=
    bucket: blog.emillon.org
    region: eu-west-1
    skip_cleanup: true
    local-dir: _site
    acl: public_read
    on:
        repo: emillon/blog.emillon.org
        branch: master
