language: haskell
ghc: 7.8
sudo: False
install:
  - cabal sandbox init
  - cabal install --only-dependencies
cache:
  directories:
    - .cabal-sandbox
deploy:
    provider: s3
    access_key_id: AKIAJOMPPK5E3YBSZZAA
    secret_access_key:
        secure: J15oUmHCx4jAgEWgG69qKAcQFUlnxHAPqNdh6mSSO2Xx+55xKa7UaQlnI1LlBVyPYxwlmpUm8fsUIcURx3krN1P0TwJO9G6NmRG7AB23HEy6zH/fYWjYAkASDJEtGjk5fEXR9Vo4aJSAZd34RH3H/Lw68xdBoqi/gRSSIqKScUY=
    bucket: blog.emillon.org
    local-dir: _site
    acl: public_read
    on:
        repo: emillon/blog.emillon.org
        branch: master
