install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ghc linkchecker python-cssutils python-utidylib
  - cabal install hakyll
before_script:
  - ghc --make blog
  - ./blog build
script: "linkchecker --check-html --check-css --anchors _site"
