install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ghc libghc-hakyll-dev linkchecker python-cssutils python-utidylib
before_script:
  - ghc --make blog
  - ./blog build
script: "linkchecker --check-html --check-css --anchors _site"
