install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ghc libghc-hakyll-dev linkchecker
before_script:
  - ghc --make blog
  - ./blog build
script: "linkchecker --no-warnings --check-html --check-css --anchors _site"
