#!/usr/bin/env python
from slugify import slugify
import os
import sys
import time


def parse_header(lines):
    separator = '---'
    assert (lines[0].strip() == separator)
    header = {}
    for l in lines[1:]:
        l = l.strip()
        if l == separator:
            return header
        k, v = l.split(':')
        header[k] = v.strip()
    assert False


def main():
    fname = sys.argv[1]
    with open(fname) as f:
        contents = f.readlines()
    header = parse_header(contents)
    tags = header.get('tags', None)
    assert tags, "No tags!"
    title = header['title']
    slug = slugify(unicode(title))
    today = time.strftime("%Y-%m-%d")
    fullslug = '{date}-{slug}'.format(date=today, slug=slug)
    slugtitle = fullslug + '.mdwn'
    dest = os.path.join('posts', slugtitle)
    os.rename(fname, dest)
    asset_dir = os.path.splitext(fname)[0]
    if os.path.isdir(asset_dir):
        asset_dir_dest = os.path.join('posts', fullslug)
        os.rename(asset_dir, asset_dir_dest)

if __name__ == '__main__':
    main()
