name: CI

on:
  - push
  - pull_request

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix fmt
      - run: nix develop .#new -c dune fmt

  nix:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix run .# -- build
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site

  nix:
    name: Build (new)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix develop .#new -c dune runtest
