# This Github Actions workflow is modified from
# https://kodimensional.dev/github-actions
name: 'CI'

# Trigger the workflow on push or pull request, but only for the master branch
on: [push, pull_request]

jobs:
  nix:
    name: Build (nix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix run --impure .# -- build
        env:
          NIXPKGS_ALLOW_UNFREE: 1

  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      with:
        stack-version: "latest"
        enable-stack: true
        stack-no-global: true

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}

    - name: Test (Ubuntu)
      run: |
        stack test --no-terminal --fast --stack-yaml stack.yaml

    - name: Build
      run: |
        stack exec --no-terminal --stack-yaml stack.yaml blog build

    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: _site
